apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thaiha-guestbook-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thaiha-hub/LE_guestbook_ArgoCD
    targetRevision: minikube
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: grupp2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
